Repository tonicpow/widget, pull requests merged in 2021-03, with the labels that each got.

#36 Feature: Events Service
  dist/tonicpow.js
  dist/widget.js
  package-lock.json
  package.json
  src/config.js
  src/events.js
  src/index.js
Labels: feature, update

#37 Use prettier, commit hooks
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general.md
  .github/dependabot.yml
  .github/workflows/main-ci.yml
  .goreleaser.yml
  .prettierignore
  CODE_OF_CONDUCT.md
  README.md
  dist/tonicpow.js
  dist/widget.js
  examples/basic/basic-example.html
  package-lock.json
  package.json
  src/config.js
  src/events.js
  src/index.js
  src/storage.js
  test/test.js
  test/testrunner.html
  webpack.config.js
  yarn.lock
Labels: refactor, update

#38 Converted to Typescript
  dist/tonicpow.js
  dist/widget.js
  examples/basic/basic-example.html
  package-lock.json
  package.json
  src/assets/image_placeholder_tonicpow_square.svg
  src/config.js
  src/config.ts
  src/events.js
  src/events.ts
  src/index.js
  src/index.ts
  src/storage.js
  src/storage.ts
  src/types/custom.d.ts
  src/types/index.d.ts
  test/test.js
  test/test.ts
  test/testrunner.html
  tsconfig.json
  webpack.config.js
Labels: refactor, update

#41 Send Ping Event
  dist/tonicpow.js
  dist/widget.js
  src/events.ts
  src/index.ts
  src/types/index.d.ts
Labels: feature, update

#42 test + lint
  .eslintrc.json
  dist/tonicpow.js
  dist/widget.js
  package-lock.json
  package.json
  src/assets/image_placeholder_tonicpow_square.svg
  src/config.ts
  src/events.ts
  src/index.ts
  src/storage.ts
  src/types/index.d.ts
  test/test.ts
  tsconfig.json
Labels: refactor, test, update
